name: Set up Node.js
description: Checkout repository and set up Node.js
inputs:
  fetch-depth:
    description: Number of commits to fetch
    required: false
    default: "1"
  node-version:
    description: Node.js version
    required: false
    default: "lts/*"
  npm-registry:
    description: npm registry URL
    required: false
  npm-scope:
    description: npm registry scope
    required: false
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4 #https://github.com/actions/checkout/releases
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Set up Node.js
      uses: actions/setup-node@v4 #https://github.com/actions/setup-node/releases
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.npm-registry }}
        scope: ${{ inputs.npm-scope }}
