version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '11:00'
      timezone: Europe/Berlin
    assignees:
      - Renaud-R-Koerber
      - MikeKlingbielKoerber
    reviewers:
      - Renaud-R-Koerber
      - MikeKlingbielKoerber
    commit-message:
      prefix: chore(github-actions)
    groups:
      github-actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
