name: Cache yarn dependencies
description: Cache yarn dependencies
inputs:
  path:
    description: A list of files to cache and restore
    required: true
  key:
    description: An explicit key for a cache entry
    required: false
    default: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
runs:
  using: composite
  steps:
    - name: Cache yarn dependencies
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      id: yarn-cache
      with:
        path: ${{ input.path }}
        key: ${{ input.key }}
